package cz.ligas.exportoverview.gui;

import cz.ligas.exportoverview.appli.ClientOps;
import cz.ligas.exportoverview.appli.ExportLineOps;
import cz.ligas.exportoverview.appli.WarehouseItemOps;
import java.beans.Beans;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author xligas
 */
public class WarehouseForm extends javax.swing.JFrame {

    /** Creates new form WarehouseForm */
    public WarehouseForm() {
        initComponents();
        myInit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExportOverviewPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ExportOverviewPU").createEntityManager();
        warehouseItemQuery = java.beans.Beans.isDesignTime() ? null : ExportOverviewPUEntityManager.createQuery("SELECT w FROM WarehouseItem w");
        warehouseItemList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : warehouseItemQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        warehouseTable = new javax.swing.JTable();
        warehouseTableL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        warehouseTable.setName("warehouseTable"); // NOI18N
        jScrollPane1.setViewportView(warehouseTable);

        warehouseTableL.setText("Product in the warehouse:");
        warehouseTableL.setName("warehouseTableL"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addComponent(warehouseTableL))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warehouseTableL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(WarehouseForm.class);
        warehouseTableL.getAccessibleContext().setAccessibleName(resourceMap.getString("warehouseTableL.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ExportOverviewPUEntityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<cz.ligas.exportoverview.db.WarehouseItem> warehouseItemList;
    private javax.persistence.Query warehouseItemQuery;
    private javax.swing.JTable warehouseTable;
    private javax.swing.JLabel warehouseTableL;
    // End of variables declaration//GEN-END:variables
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;


    private void myInit() {
        bindingGroup = new BindingGroup();
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cz.ligas.exportoverview.gui.GuiMain.class).getContext().getResourceMap(WarehouseForm.class);
        try {
            warehouseItemList = Beans.isDesignTime() ? (ObservableList) Collections.emptyList() : ObservableCollections.observableList(WarehouseItemOps.getWarehouseItems());
        } catch (Exception ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JTableBinding warehouseTableBinding = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE, warehouseItemList, warehouseTable);
        JTableBinding.ColumnBinding columnBinding;
        columnBinding = warehouseTableBinding.addColumnBinding(ELProperty.create("${productItem.productCode}"));
        columnBinding.setColumnName(resourceMap.getString("warehouseTable.columnModel.productCode"));
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = warehouseTableBinding.addColumnBinding(ELProperty.create("${productItem.productName}"));
        columnBinding.setColumnName(resourceMap.getString("warehouseTable.columnModel.productName"));
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = warehouseTableBinding.addColumnBinding(ELProperty.create("${productItem.productPrice}"));
        columnBinding.setColumnName(resourceMap.getString("warehouseTable.columnModel.productPrice"));
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = warehouseTableBinding.addColumnBinding(ELProperty.create("${productCount}"));
        columnBinding.setColumnName(resourceMap.getString("warehouseTable.columnModel.productCount"));
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(warehouseTableBinding);
        warehouseTableBinding.bind();
        bindingGroup.bind();
    }

}
