package cz.ligas.exportoverview.gui;

import cz.ligas.exportoverview.appli.CategoryOps;
import cz.ligas.exportoverview.appli.ExportLineOps;
import cz.ligas.exportoverview.db.Clients;
import cz.ligas.exportoverview.db.ExportLine;
import cz.ligas.exportoverview.db.ProductCategory;
import cz.ligas.exportoverview.db.Products;
import java.beans.Beans;
import java.text.ParseException;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author xligas
 */
public class AddProductForm extends javax.swing.JDialog {

    Clients clinets = new Clients();

    /** Creates new form AddProductForm */
    public AddProductForm(Clients c,java.awt.Frame parent) {
        super(parent);
        initComponents();
        myInit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        categoryComboBox = new javax.swing.JComboBox();
        productComboBox = new javax.swing.JComboBox();
        nExportLineSendIn = new javax.swing.JTextField();
        nExportLineSoldIn = new javax.swing.JTextField();
        addExportLineButton = new javax.swing.JButton();
        categoryL = new javax.swing.JLabel();
        productL = new javax.swing.JLabel();
        exportLineSendL = new javax.swing.JLabel();
        exportLineSoldL = new javax.swing.JLabel();
        mExportLineSpecialPriceIn = new javax.swing.JTextField();
        exportLineCustomPriceL = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AddProductForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox.setName("categoryComboBox"); // NOI18N

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.setName("productComboBox"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedItem.products}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, categoryComboBox, eLProperty, productComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        nExportLineSendIn.setText(resourceMap.getString("nExportLineSendIn.text")); // NOI18N
        nExportLineSendIn.setName("nExportLineSendIn"); // NOI18N

        nExportLineSoldIn.setText(resourceMap.getString("nExportLineSoldIn.text")); // NOI18N
        nExportLineSoldIn.setName("nExportLineSoldIn"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(AddProductForm.class, this);
        addExportLineButton.setAction(actionMap.get("addExportLine")); // NOI18N
        addExportLineButton.setText(resourceMap.getString("addExportLineButton.text")); // NOI18N
        addExportLineButton.setName("addExportLineButton"); // NOI18N

        categoryL.setText(resourceMap.getString("categoryL.text")); // NOI18N
        categoryL.setName("categoryL"); // NOI18N

        productL.setText(resourceMap.getString("productL.text")); // NOI18N
        productL.setName("productL"); // NOI18N

        exportLineSendL.setText(resourceMap.getString("exportLineSendL.text")); // NOI18N
        exportLineSendL.setName("exportLineSendL"); // NOI18N

        exportLineSoldL.setText(resourceMap.getString("exportLineSoldL.text")); // NOI18N
        exportLineSoldL.setName("exportLineSoldL"); // NOI18N

        mExportLineSpecialPriceIn.setName("mExportLineSpecialPriceIn"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.productPrice}"), mExportLineSpecialPriceIn, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        exportLineCustomPriceL.setText(resourceMap.getString("exportLineCustomPriceL.text")); // NOI18N
        exportLineCustomPriceL.setName("exportLineCustomPriceL"); // NOI18N

        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addExportLineButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productL)
                                    .addComponent(categoryL)
                                    .addComponent(exportLineSoldL)
                                    .addComponent(exportLineSendL))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exportLineCustomPriceL, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryComboBox, 0, 309, Short.MAX_VALUE)
                            .addComponent(productComboBox, 0, 309, Short.MAX_VALUE)
                            .addComponent(nExportLineSendIn, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(nExportLineSoldIn, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(mExportLineSpecialPriceIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryL)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productL)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mExportLineSpecialPriceIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineCustomPriceL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nExportLineSendIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineSendL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nExportLineSoldIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineSoldL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addExportLineButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExportLineButton;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel categoryL;
    private javax.swing.JLabel exportLineCustomPriceL;
    private javax.swing.JLabel exportLineSendL;
    private javax.swing.JLabel exportLineSoldL;
    private javax.swing.JTextField mExportLineSpecialPriceIn;
    private javax.swing.JTextField nExportLineSendIn;
    private javax.swing.JTextField nExportLineSoldIn;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JLabel productL;
    private javax.swing.JLabel titleLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private List<ProductCategory> categoryList;
    private MyInputVerifier verifier = new MyInputVerifier();

    private void myInit() {
        bindingGroup = new BindingGroup();
        nExportLineSendIn.setInputVerifier(verifier);
        nExportLineSendIn.addActionListener(verifier);
        exportLineSendL.setLabelFor(nExportLineSendIn);
        nExportLineSoldIn.setInputVerifier(verifier);
        nExportLineSoldIn.addActionListener(verifier);
        exportLineSoldL.setLabelFor(exportLineSoldL);
        mExportLineSpecialPriceIn.setInputVerifier(verifier);
        mExportLineSpecialPriceIn.addActionListener(verifier);
        exportLineCustomPriceL.setLabelFor(mExportLineSpecialPriceIn);
        try {
            categoryList = Beans.isDesignTime() ? (ObservableList) Collections.emptyList() : ObservableCollections.observableList(CategoryOps.getCategories());
        } catch (Exception ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, categoryList, categoryComboBox);
        bindingGroup.addBinding(jComboBoxBinding);
        bindingGroup.bind();
    }

    @Action
    public void addExportLine(){
        try {
            ExportLine el = new ExportLine();
            el.setProd((Products) productComboBox.getSelectedItem());
            el.setClient(clinets);
            el.setSentPrice(MyParser.paresePrice(mExportLineSpecialPriceIn.getText()));
            el.setSent(MyParser.pareseIntNumber(nExportLineSendIn.getText()));
            el.setSold(MyParser.pareseIntNumber(nExportLineSoldIn.getText()));
            ExportLineOps.addExportLine(el);
            //ExportOps.recalculateExport(clinets);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AddProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
