/*
 * AddProductForm.java
 *
 * Created on 5.8.2009, 10:30:48
 */
package cz.ligas.exportoverview.gui;

import cz.ligas.exportoverview.appli.CategoryOps;
import cz.ligas.exportoverview.appli.ExportLineOps;
import cz.ligas.exportoverview.appli.ExportOps;
import cz.ligas.exportoverview.db.Export;
import cz.ligas.exportoverview.db.ExportLine;
import cz.ligas.exportoverview.db.ProductCategory;
import cz.ligas.exportoverview.db.Products;
import java.beans.Beans;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;
// TODO: refresh po pridani produktu

/**
 *
 * @author xligas
 */
public class AddProductForm extends javax.swing.JFrame {

    /** Creates new form AddProductForm */
    public AddProductForm(Export ex) {
        this.export = ex;
        initComponents();
        myInit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        categoryComboBox = new javax.swing.JComboBox();
        productComboBox = new javax.swing.JComboBox();
        exportLineSendIn = new javax.swing.JTextField();
        exportLineSoldIn = new javax.swing.JTextField();
        addExportLineButton = new javax.swing.JButton();
        categoryL = new javax.swing.JLabel();
        productL = new javax.swing.JLabel();
        exportLineSendL = new javax.swing.JLabel();
        exportLineSoldL = new javax.swing.JLabel();
        exportLineSpecialPriceIn = new javax.swing.JTextField();
        exportLineCustomPriceL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox.setName("categoryComboBox"); // NOI18N

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.setName("productComboBox"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedItem.products}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, categoryComboBox, eLProperty, productComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cz.ligas.exportoverview.gui.GuiMain.class).getContext().getResourceMap(AddProductForm.class);
        exportLineSendIn.setText(resourceMap.getString("exportLineSendIn.text")); // NOI18N
        exportLineSendIn.setName("exportLineSendIn"); // NOI18N

        exportLineSoldIn.setText(resourceMap.getString("exportLineSoldIn.text")); // NOI18N
        exportLineSoldIn.setName("exportLineSoldIn"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cz.ligas.exportoverview.gui.GuiMain.class).getContext().getActionMap(AddProductForm.class, this);
        addExportLineButton.setAction(actionMap.get("addExportLine")); // NOI18N
        addExportLineButton.setText(resourceMap.getString("addExportLineButton.text")); // NOI18N
        addExportLineButton.setName("addExportLineButton"); // NOI18N

        categoryL.setText(resourceMap.getString("categoryL.text")); // NOI18N
        categoryL.setName("categoryL"); // NOI18N

        productL.setText(resourceMap.getString("productL.text")); // NOI18N
        productL.setName("productL"); // NOI18N

        exportLineSendL.setText(resourceMap.getString("exportLineSendL.text")); // NOI18N
        exportLineSendL.setName("exportLineSendL"); // NOI18N

        exportLineSoldL.setText(resourceMap.getString("exportLineSoldL.text")); // NOI18N
        exportLineSoldL.setName("exportLineSoldL"); // NOI18N

        exportLineSpecialPriceIn.setName("exportLineSpecialPriceIn"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.productPrice}"), exportLineSpecialPriceIn, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        exportLineCustomPriceL.setText(resourceMap.getString("exportLineCustomPriceL.text")); // NOI18N
        exportLineCustomPriceL.setName("exportLineCustomPriceL"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addExportLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productL)
                                    .addComponent(categoryL)
                                    .addComponent(exportLineSoldL)
                                    .addComponent(exportLineSendL))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exportLineCustomPriceL, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryComboBox, 0, 309, Short.MAX_VALUE)
                            .addComponent(productComboBox, 0, 309, Short.MAX_VALUE)
                            .addComponent(exportLineSendIn, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(exportLineSoldIn, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(exportLineSpecialPriceIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryL)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productL)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLineSpecialPriceIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineCustomPriceL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLineSendIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineSendL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLineSoldIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLineSoldL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addExportLineButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExportLineButton;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel categoryL;
    private javax.swing.JLabel exportLineCustomPriceL;
    private javax.swing.JTextField exportLineSendIn;
    private javax.swing.JLabel exportLineSendL;
    private javax.swing.JTextField exportLineSoldIn;
    private javax.swing.JLabel exportLineSoldL;
    private javax.swing.JTextField exportLineSpecialPriceIn;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JLabel productL;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private List<ProductCategory> categoryList;
    private Export export;

    private void myInit() {
        bindingGroup = new BindingGroup();
        try {
            categoryList =Beans.isDesignTime() ? (ObservableList) Collections.emptyList() : ObservableCollections.observableList( CategoryOps.getCategories());
        } catch (Exception ex) {
            Logger.getLogger(ProductForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JComboBoxBinding jComboBoxBinding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, categoryList, categoryComboBox);
        bindingGroup.addBinding(jComboBoxBinding);
        bindingGroup.bind();
    }
    // TODO: manualne plnenie produktComboBoxu

    @Action
    public void addExportLine() {
        ExportLine el = new ExportLine();
        el.setProd((Products) productComboBox.getSelectedItem());
        el.setExport(export);
        el.setPrice(Float.parseFloat(exportLineSpecialPriceIn.getText()));
        el.setSent(Integer.parseInt(exportLineSendIn.getText()));
        el.setSold(Integer.parseInt(exportLineSoldIn.getText()));
        //overenie vyplnenia
        try {
            ExportLineOps.addExportLine(el);
        } catch (Exception ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        ExportOps.recalculateExport(export);
        this.dispose();
    }
}
