package cz.ligas.exportoverview.gui;

import cz.ligas.exportoverview.appli.CategoryOps;
import cz.ligas.exportoverview.db.ProductCategory;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;

/**
 *
 * @author xligas
 */
public class CategoryForm extends javax.swing.JDialog {

    /** Creates new form CategoryForm */
    public CategoryForm(java.awt.Frame parent) {
        super(parent);
        initComponents();
        myInit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryCodeL = new javax.swing.JLabel();
        categoryNameL = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        tCategoryCodeIn = new javax.swing.JTextField();
        tCategoryNameIn = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(CategoryForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        categoryCodeL.setText(resourceMap.getString("categoryCodeL.text")); // NOI18N
        categoryCodeL.setName("categoryCodeL"); // NOI18N

        categoryNameL.setText(resourceMap.getString("categoryNameL.text")); // NOI18N
        categoryNameL.setName("categoryNameL"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(CategoryForm.class, this);
        saveButton.setAction(actionMap.get("saveCategory")); // NOI18N
        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N

        tCategoryCodeIn.setText(resourceMap.getString("tCategoryCodeIn.text")); // NOI18N
        tCategoryCodeIn.setName("tCategoryCodeIn"); // NOI18N

        tCategoryNameIn.setText(resourceMap.getString("tCategoryNameIn.text")); // NOI18N
        tCategoryNameIn.setName("tCategoryNameIn"); // NOI18N

        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryNameL)
                            .addComponent(categoryCodeL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCategoryCodeIn, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(tCategoryNameIn, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addComponent(titleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryCodeL)
                    .addComponent(tCategoryCodeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryNameL)
                    .addComponent(tCategoryNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void saveCategory() {
        ProductCategory pc = new ProductCategory();
        pc.setCategoryCode(tCategoryCodeIn.getText());
        pc.setCategoryName(tCategoryNameIn.getText());
        //overenie vyplnenia
        try {
            CategoryOps.addCategory(pc);
        }catch (javax.persistence.RollbackException sqlEx){
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, sqlEx);
            MyUtilErrorClass.errorDialog("error.sql.rollback");
        }catch (Exception ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryCodeL;
    private javax.swing.JLabel categoryNameL;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tCategoryCodeIn;
    private javax.swing.JTextField tCategoryNameIn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    private MyInputVerifier verifier = new MyInputVerifier();

    private void myInit() {
        tCategoryCodeIn.setInputVerifier(verifier);
        tCategoryCodeIn.addActionListener(verifier);
        categoryCodeL.setLabelFor(tCategoryCodeIn);
        tCategoryNameIn.setInputVerifier(verifier);
        tCategoryNameIn.addActionListener(verifier);
        categoryNameL.setLabelFor(tCategoryNameIn);
    }
}
