/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditExportLineForm.java
 *
 * Created on 9.8.2009, 11:56:22
 */
package cz.ligas.exportoverview.gui;

import cz.ligas.exportoverview.appli.ExportLineOps;
import cz.ligas.exportoverview.appli.ExportOps;
import cz.ligas.exportoverview.db.Export;
import cz.ligas.exportoverview.db.ExportLine;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;

/**
 *
 * @author xligas
 */
public class EditExportLineForm extends javax.swing.JFrame {

    /** Creates new form EditExportLineForm */
    public EditExportLineForm(Export exp, ExportLine el) {
        this.export = exp;
        this.exportLine = el;
        initComponents();
        myInit();
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        exportLineSentL = new javax.swing.JLabel();
        exportLineSoldL = new javax.swing.JLabel();
        nExportLineSentSpinner = new javax.swing.JSpinner();
        nExportLineSoldSpinner = new javax.swing.JSpinner();
        exportLineSaveButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditExportLineForm.class);
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        exportLineSentL.setText(resourceMap.getString("exportLineSentL.text")); // NOI18N
        exportLineSentL.setName("exportLineSentL"); // NOI18N

        exportLineSoldL.setText(resourceMap.getString("exportLineSoldL.text")); // NOI18N
        exportLineSoldL.setName("exportLineSoldL"); // NOI18N

        nExportLineSentSpinner.setName("nExportLineSentSpinner"); // NOI18N

        nExportLineSoldSpinner.setName("nExportLineSoldSpinner"); // NOI18N

	javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cz.ligas.exportoverview.gui.GuiMain.class).getContext().getActionMap(EditExportLineForm.class, this);
        exportLineSaveButton.setAction(actionMap.get("editExportLineSaveAction")); // NOI18N
        
	exportLineSaveButton.setText(resourceMap.getString("exportLineSaveButton.text")); // NOI18N
        exportLineSaveButton.setName("exportLineSaveButton"); // NOI18N

        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportLineSaveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exportLineSentL)
                            .addComponent(exportLineSoldL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nExportLineSoldSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(nExportLineSentSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addComponent(titleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLineSentL)
                    .addComponent(nExportLineSentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportLineSoldL)
                    .addComponent(nExportLineSoldSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportLineSaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportLineSaveButton;
    private javax.swing.JLabel exportLineSentL;
    private javax.swing.JLabel exportLineSoldL;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JSpinner nExportLineSentSpinner;
    private javax.swing.JSpinner nExportLineSoldSpinner;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    private ExportLine exportLine;
    private Export export;
    private MyInputVerifier verifier = new MyInputVerifier();

    @Action
    public void editExportLineSaveAction() {
        int send = Integer.parseInt(nExportLineSentSpinner.getValue().toString());
        int sold = Integer.parseInt(nExportLineSoldSpinner.getValue().toString());
        try {
            ExportLineOps.editExportLine(export,exportLine,send,sold);
        } catch (Exception ex) {
            Logger.getLogger(EditExportLineForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        ExportOps.recalculateExport(export);
        this.dispose();
        System.err.println("editExportLineSaveAction executed");
    }

    private void myInit() {
        nExportLineSentSpinner.setInputVerifier(verifier);
        exportLineSentL.setLabelFor(nExportLineSentSpinner);
        nExportLineSoldSpinner.setInputVerifier(verifier);
        exportLineSoldL.setLabelFor(nExportLineSoldSpinner);

    }
}
